#Distribución y versión de ésta
FROM ubuntu:latest

#Autor
MAINTAINER Juan Jesús Tomás R.

#Actualiza repositorios e instala: postgresql
RUN apt-get update && apt-get install -y postgresql postgresql-contrib

#Configuración de la base de datos
#Creamos la base de datos, el suario y la contraseña
USER postgres
RUN /etc/init.d/postgresql start \
    && psql --command "CREATE USER baresytapasuser WITH SUPERUSER PASSWORD 'baresyTapasPassword';" \
    && createdb -O baresytapasuser baresytapas

#Como root, completamos la configuración
USER root
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.5/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf

#Exponemos el puerto por defecto
EXPOSE 5432
